// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UsageDemo.DataAcessLayer;

#nullable disable

namespace UsageDemo.Migrations
{
    [DbContext(typeof(UsageDbContext))]
    partial class UsageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UsageDemo.Models.Usage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UsageCharge")
                        .HasColumnType("text");

                    b.Property<DateTime>("UsageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsageKey")
                        .HasColumnType("text");

                    b.Property<string>("UsageName")
                        .HasColumnType("text");

                    b.Property<string>("UsageServices")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UsageInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
